openapi: 3.1.0
info:
  title: CineWinx API
  version: 1.0.0
  contact:
    name: Gabriel Maia
    email: gabrielmaialva33@gmail.com
    url: https://t.me/mrootx
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: >
    This is an API for a CineWinx channel in Telegram. It provides a list of movies and series that can be watched online.

    # Introduction
    The CineWinx API is a RESTful API that provides a list of movies and series that can be watched online. The API is designed to be simple and easy to use, with a focus on providing a clean and consistent interface for developers to work with.

servers:
  - url: http://localhost:3333
    description: Local server
tags:
  - name: Movies
    description: Operations related to movies
paths:
  /movies:
    get:
      tags:
        - Movies
      summary: Get a list of movies
      description: Returns a list of movies that can be watched online
      responses:
        '200':
          description: A list of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          format: int64
